#!/usr/bin/env python3
"""Generate docs/SCHEDULER_INVENTORY.md from LIVE state: crontab -l plus every
~/Library/LaunchAgents/com.atom.*.plist. Flags any script scheduled by BOTH.

WHY: a hand-written inventory goes stale exactly the way crontab_VN_anchored.txt
did, and that staleness caused the Jul-26 incident (installing a May-era file
destroyed 11 live jobs). This reads reality every time it runs.
"""
import plistlib
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENTS = Path.home() / "Library" / "LaunchAgents"


def script_of(cmd: str) -> str:
    m = re.findall(r"[\w./-]+\.(?:sh|py)", cmd)
    return Path(m[-1]).name if m else cmd.split()[-1][:40]


def main():
    cron = []
    out = subprocess.run(["crontab", "-l"], capture_output=True, text=True).stdout
    for line in out.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" in s.split()[0]:
            continue
        if not re.match(r"^[\d*]", s):
            continue
        parts = s.split(None, 5)
        cron.append((" ".join(parts[:5]), parts[5] if len(parts) > 5 else "", script_of(s)))

    agents = []
    for p in sorted(AGENTS.glob("com.atom.*.plist")):
        d = plistlib.loads(p.read_bytes())
        sched = d.get("StartCalendarInterval")
        if isinstance(sched, dict):
            sched = [sched]
        if sched:
            desc = "; ".join(f"{x.get('Hour','*'):>02}:{x.get('Minute',0):02}"
                             + (f" wd{x['Weekday']}" if "Weekday" in x else "")
                             for x in sched)
        elif "StartInterval" in d:
            desc = f"every {d['StartInterval']}s"
        else:
            desc = "on-demand"
        prog = (d.get("ProgramArguments") or [d.get("Program", "?")])[-1]
        agents.append((d.get("Label", p.stem), desc, script_of(str(prog)),
                       d.get("StandardOutPath", "")))

    cron_scripts = {c[2] for c in cron}
    dupes = sorted(cron_scripts & {a[2] for a in agents})

    md = [f"# SCHEDULER INVENTORY (generated {datetime.now():%Y-%m-%d %H:%M})",
          "", "*Generated by `scripts/scheduler_inventory.py` from live state.*",
          "*Rule: exactly ONE scheduler per job. Re-run after any change.*", ""]
    if dupes:
        md += ["## DUPLICATES -- scheduled by BOTH cron and launchd", ""]
        md += [f"- **{d}**" for d in dupes] + [""]
    else:
        md += ["**No duplicates: every job has exactly one owner.**", ""]
    md += ["## launchd agents", "", "| label | schedule | script | log |", "|---|---|---|---|"]
    md += [f"| {l} | {s} | `{sc}` | {lg.split('/')[-1] if lg else '-'} |"
           for l, s, sc, lg in agents]
    md += ["", f"## cron ({len(cron)} active)", "", "| schedule | script |", "|---|---|"]
    md += [f"| `{sched}` | `{sc}` |" for sched, _, sc in cron]

    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "SCHEDULER_INVENTORY.md").write_text("\n".join(md) + "\n")
    print(f"{len(cron)} cron job(s), {len(agents)} launchd agent(s), "
          f"{len(dupes)} duplicate(s) -> docs/SCHEDULER_INVENTORY.md")
    return 1 if dupes else 0


if __name__ == "__main__":
    sys.exit(main())
