name: Seed Forecast Accuracy

on:
  schedule:
    - cron: '10 1 * * *'        # run ~10 mins after retrain
  workflow_dispatch:

permissions:
  contents: write               # needed to push DB back to repo

concurrency:
  group: seed-accuracy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  seed-accuracy-db:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check paths
        run: |
          echo "CWD:"; pwd
          echo "Top-level:"; ls -la
          echo "forecast_eval/:"; ls -la forecast_eval || true
          echo "CSV at repo root?"; test -f forecast_metrics.csv && echo "✅ found" || echo "❌ missing"

      - name: Show seed_db.py header & help
        working-directory: forecast_eval
        run: |
          sed -n '1,120p' seed_db.py || true
          python -u seed_db.py --help || true

      - name: Seed accuracy DB
        working-directory: forecast_eval
        run: |
          set -euxo pipefail
          CSV="../forecast_metrics.csv"
          if [ ! -f "$CSV" ]; then
            echo "No $CSV found; nothing to seed. Exiting cleanly."
            exit 0
          fi
          # Preferred invocation; adjust if --help shows different flags
          python -u seed_db.py --csv "$CSV" --out forecast_accuracy.db
          test -f forecast_accuracy.db

      - name: Move DB to repo root
        working-directory: forecast_eval
        run: mv -f forecast_accuracy.db ..

      - name: Commit & push seeded DB
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add forecast_accuracy.db
          git commit -m "Nightly: update forecast_accuracy.db ($(date -u +'%Y-%m-%d'))" || echo "No changes to commit"
          git push
