[server]
headless = true
# enableXsrfProtection defaults to true; keep it.
# Remove or comment out any `enableCORS` override.
fileWatcherType = "poll"
port = 8501

# Optional theme block
[theme]
base = "light"
