app_password = "MlQ@nt@072025"
NEWS_API_KEY = "4013dbfd25eb4050b4013f394dee8683"

# Congress Trading
QUIVER_API_KEY        = "UI3Jr1HuYwu5BXXae9nkMnk2tua9eq9KECJyQXuO"
ALPHA_VANTAGE_KEY     = "207XMC6GUSV0NA3S"
MARKETAUX_API_KEY     = "UI3Jr1HuYwu5BXXae9nkMnk2tua9eq9KECJyQXuO"


# Insider‐pipeline DB (features, holdings, trades, etc.)
insider_db_url  = "sqlite:///forecast.db"


# Forecast-accuracy DB (evaluation metrics)
accuracy_db_url = "sqlite:///forecast_accuracy.db"



[gcp_service_account]
type = "service_account"
project_id = "mlquan"
private_key_id = "0515c30186b62fa8be58a96cdea9e18df02aac7c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC+FqCf3QYTr1cf
zz8j46gjFglemuyFLZWJzsf9XAZG9IdQ+W9bTYL+rPRwraTgVPxAxBWidY1le2rg
71B/zbyZYhsOAXMBPKkCrLtiguWGp3yy+D2cSUcPNuOTN1IlAFA66d/PSncoL7rl
e85VV7mGVI95ApkiYNiteDUhhEGf2xGLzs2TugzpISDpIOPvdGUoeH1fhB/bJ//E
EidB1A8khs000Y+XQESoBUp3NPk6xUlhIxwSH/00CIkORg9629kjT5C7NHDij5Hq
DewTKUJb7PEBd87wYkd/jlW8MR4iJJEWT4W7iwcJOuR4Z6QjwVQ495EfZ+8VvTVN
vQwp4nVpAgMBAAECggEACM0Ou3gbS5axsk+r0mM8VKuKMYQmG/XEAlu9l2BxtfVP
vT20nIXr4RNsRI9K8/awsJBORCBXNJyl59Y3ZENyo6i5gfN/5KMaBtKtNl7DIRyT
bHc2kGGK1bcqiuq5IJdxdNjWkPLCA5f6JPKPghS2tUkoVLz8ZBgXJX5MT3Sf0+Es
jNgn4OmwO9Kuvtpd97PlxlMz0ecbPpmq5WSpTu2WZ/APePcLN9huwGmV5ju38Bfg
xlVmspQT98f9UyHXJQ+0Xa84jq7h7n5nSuG9fz/7665N7+L8yi93jcUpACmSeWYp
ap3iHZqoxBhfzysDDvNZgN/sqHTW3IBz+hGJzYzPJQKBgQDvDldIeGv7G97u3zLj
qNEWa57M8DhCrlxmHL23/47vzx+fqrIbU7AuDu3wP/6TZaafIMYjlWmJs9fHLuoC
76bJOEPLWjspjqUV7j9M4/oqezfrcYcR8TWRhlPN/qHcpq5PcVOzs/glf8MPwSrD
1/HKvR0qOqvbHvsT4OBbViWkXwKBgQDLj8V4lhi8mnnqI+8AISI9pgRIX00BKyS8
LtyhIHKDH9/fo0bzcZKgC9TCiaTZUdvpwzPotkxwa0yIk5VW6ICtCM5xf0fp7dSt
4I22BUwEXF8OGGz7qt6btxSOUnLTjbAew1Suqp6Tr6zEBX1tMYmyzhqPlTff/iDH
asQCiz37NwKBgGIU5zjjt6ISoFgvmYiQtiDVzRTWpq6tLVn0Bt8can/34ki3V1Yg
8xMiqvs8tm2xcjit0L2+ystlz2140SidPTgn7qDbh5SYYyFpW+1nSDfv0FS4gquY
5NqtW2sUQ0Lt3GzZ2XbMq05vag/nuG0cB6egCfxOkD5aKrfQNx0iblVPAoGAWBwH
/nUBiglXQdiB581vs717VxQhEaNqCCZEi12vE0Clt3hGCrObIrlcQ0Qu3X4IMTuz
6UOW/IYFH4y59F846yzHpurP5tpx1z0+OY47ZBvTbRd3fMtuBXqOZDgdyaInnHkx
21SwxP4iSsqRisUJdCKv7nxJLiQibg6xfuRkVKsCgYEAxFTEEdVPUXPyK8GFj2E7
gyUhkrR9jzBK8oENkiIgClrTXnFJVRsE5xPbJ23qYO9HbsYnal6RQ+Hj6IMeJtDT
v6Kgqlcvd7Mca8MTjpRVlb2Y9+8yUgezHyZMo3Y14KTxNnRm0IDhFJQZvZMqikuC
fCkv/+LTMOw24aGs+GyE2zE=
-----END PRIVATE KEY-----"""
client_email = "ml-forecast-logger@mlquan.iam.gserviceaccount.com"
client_id = "111716060365810714194"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ml-forecast-logger@mlquan.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


# Congress Trading
QUIVER_API_KEY = "UI3Jr1HuYwu5BXXae9nkMnk2tua9eq9KECJyQXuO"
